--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.76.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 21/12/2017 15:25:15
-- Server version: 5.7.14
-- Client version: 4.1
--


DROP DATABASE IF EXISTS estagio;
CREATE DATABASE estagio
	CHARACTER SET utf8
	COLLATE utf8_general_ci;

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

USE estagio;

CREATE TABLE bd_usuario (
  idusuario INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  nome_usuario VARCHAR(45) NOT NULL,
  senha VARCHAR(45) NOT NULL,
  PRIMARY KEY (idusuario)
)
ENGINE = INNODB
AUTO_INCREMENT = 7
AVG_ROW_LENGTH = 5461
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

CREATE TABLE evento (
  idevento INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  nome_evento VARCHAR(255) NOT NULL,
  descricao_evento VARCHAR(255) NOT NULL,
  data_inicio DATE NOT NULL,
  data_fim DATE NOT NULL,
  nome_coord_curso VARCHAR(55) NOT NULL,
  nome_coor_falect VARCHAR(55) NOT NULL,
  numero_protocolo_certificados VARCHAR(40) NOT NULL,
  num_participantes INT(3) UNSIGNED NOT NULL DEFAULT 1,
  num_comissao INT(3) UNSIGNED NOT NULL DEFAULT 1,
  num_tutores INT(3) UNSIGNED NOT NULL DEFAULT 1,
  horas_comissao INT(3) UNSIGNED NOT NULL,
  horas_maximas INT(3) UNSIGNED NOT NULL,
  horas_tutores INT(3) UNSIGNED NOT NULL,
  img_fundo VARCHAR(255) NOT NULL,
  PRIMARY KEY (idevento)
)
ENGINE = INNODB
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 910
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

CREATE TABLE pessoa (
  idpessoa INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  nomepessoa VARCHAR(55) NOT NULL,
  PRIMARY KEY (idpessoa)
)
ENGINE = INNODB
AUTO_INCREMENT = 14
AVG_ROW_LENGTH = 819
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

CREATE TABLE pessoa_atividade (
  idpessoa INT(11) UNSIGNED DEFAULT NULL,
  idativ INT(11) UNSIGNED DEFAULT NULL
)
ENGINE = INNODB
AVG_ROW_LENGTH = 1820
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

CREATE TABLE atividade (
  idativ INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  nome_ativ VARCHAR(55) NOT NULL,
  desc_ativ VARCHAR(255) NOT NULL,
  carga_horaria INT(4) NOT NULL,
  id_evento INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (idativ),
  CONSTRAINT FK_atividade_evento_idevento FOREIGN KEY (id_evento)
    REFERENCES evento(idevento) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 780
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

CREATE TABLE comissao_org (
  id_pessoa INT(10) UNSIGNED NOT NULL,
  id_evento INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (id_pessoa, id_evento),
  CONSTRAINT FK_comissao_org_aluno_idpessoa FOREIGN KEY (id_pessoa)
    REFERENCES pessoa(idpessoa) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_comissao_org_evento_idevento FOREIGN KEY (id_evento)
    REFERENCES evento(idevento) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AVG_ROW_LENGTH = 1365
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

CREATE TABLE participantes (
  id_pessoa INT(11) UNSIGNED NOT NULL,
  id_evento INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (id_pessoa, id_evento),
  CONSTRAINT FK_participantes_evento_idevento FOREIGN KEY (id_evento)
    REFERENCES evento(idevento) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_participantes_pessoa_idpessoa FOREIGN KEY (id_pessoa)
    REFERENCES pessoa(idpessoa) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AVG_ROW_LENGTH = 2730
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

CREATE TABLE tutores_ativ (
  idtutor INT(11) UNSIGNED NOT NULL,
  idatividade INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (idtutor, idatividade),
  CONSTRAINT FK_tutores_ativ_aluno_idpessoa FOREIGN KEY (idtutor)
    REFERENCES pessoa(idpessoa) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_tutores_ativ_atividade_idativ FOREIGN KEY (idatividade)
    REFERENCES atividade(idativ) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AVG_ROW_LENGTH = 585
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

INSERT INTO bd_usuario VALUES
(NULL, 'admin_', 'unematcomp');


-- Table estagio.evento does not contain any data (it is empty)


-- Table estagio.pessoa does not contain any data (it is empty)


-- Table estagio.pessoa_atividade does not contain any data (it is empty)


-- Table estagio.atividade does not contain any data (it is empty)


-- Table estagio.comissao_org does not contain any data (it is empty)


-- Table estagio.participantes does not contain any data (it is empty)


-- Table estagio.tutores_ativ does not contain any data (it is empty)

/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;